services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
      args:
        NODE_VERSION: 22.13.0
    ports:
      - "${STEEL_API_PORT:-12200}:3000"
      - "9223:9223"
    environment:
      - APP_HOST=${APP_HOST:-192.168.50.251}
      - STEEL_API_PORT=${STEEL_API_PORT:-12200}
      - DOMAIN=${DOMAIN:-${APP_HOST:-192.168.50.251}:${STEEL_API_PORT:-12200}}
      - CDP_DOMAIN=${CDP_DOMAIN:-localhost:9223}
      - CHROME_HEADLESS=${CHROME_HEADLESS:-true}
    volumes:
      - ./.cache:/app/.cache
    networks:
      - steel-network

  ui:
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    ports:
      - "5173:80"
    environment:
      - API_URL=${API_URL:-http://api:3000}
    depends_on:
      - api
    networks:
      - steel-network

networks:
  steel-network:
    name: steel-network
    driver: bridge
